### PR TITLE
Merge `JtLibrary` and `JtModules` again, preserving history.

### PR DESCRIPTION
**Pull request by riccardomurri**
This large commit merges the whole contents of repositories
`TissueMAPS/JtLibrary` and `TissueMAPS/JtModules`, preserving the
history of each.

Contents are then rearranged: source files are now split by
programming language first (with top-level directories `matlab/`,
`python/`, and `r/`) and by "package" second (with second-level dirs
`jtmodules/` and `jtlib/`).

This preserves the ability to install separate packages from the joint
repo; for instance, you would need to run `pip install .` in *both*
the `python/jtmodules/` and the `python/jtlibrary/` directories.
(Some modifications to the `setup.py` files have been necessary.)

I have kept the `handles/` directory at top-level, assuming that
handles can refer to modules written in *any* language.

### CODE REVIEW

**Comment by riccardomurri** [comment]
Of course, this PR is too large to review: I guess you'll have to take my word that it makes sense...

**Comment by jluethi** [comment]
Makes sense to me. @sparkvilla When the tests are running, can you test that pull request?

**Comment by sparkvilla** [comment]
@jluethi I can test this branch, however autotest on pull request can be run once we merge TM in a unique repo, please see on [trello](https://trello.com/c/zzlES9aB/50-clean-up-pull-requests). Otherwise it can be "tested" it on a vm.

**Comment by sparkvilla** [comment]
@riccardomurri @jluethi I have tested this feature branch on a vm with a test dataset. The workflow goes through but the **available modules** are not showing up

**Comment by riccardomurri** [comment]
> The workflow goes through but the available modules are not showing up

This seems to require a change in how the TissueMAPS/TmLibrary code discovers modules to run.  Unfortunately, the current code assumes that *all* modules reside in a single directory (`modules_home`).  While changing that to be a list of directories is straightforward, the *same* configuration parameter is used to locate the `handles/` directory -- so we must disentangle that as well...

Should not be a big deal, but definitely not the 10-minute patch that I was thinking of. :-/

**Comment by hackermd** [comment]
We could have `modules_home` pointing to the root folder (and assume that it contains a `modules` and a `handles` subfolder)

**Comment by riccardomurri** [comment]
> We could have modules_home pointing to the root folder (and assume that it contains a modules and a handles subfolder)

That's not how the modules files are laid out in this pull request...

And I would take the occasion to make the mechanism a bit more general so we can support multiple module directories (e.g., I can add a directory for locally-developed modules, or 3rd-party modules, etc.)

**Comment by riccardomurri** [comment]
Running code with this new layout requires TmLibrary modifications from https://github.com/TissueMAPS/TmLibrary/pull/45

**Comment by riccardomurri** [comment]
@jluethi @sparkvilla I have tested this PR and TissueMAPS/TmLibrary#45 with the "v0.3.3/CellVoyager_2D_Canonical" test data set and they work. (*Both* need to be applied to work -- they cannot work separately.)

**Comment by sparkvilla** [comment]
@riccardomurri This branch off master. Can we merge this first into develop?

**Comment by riccardomurri** [comment]
> This branch off master. Can we merge this first into develop?

Well, `master` and `develop` are currently at the same HEAD commit::

         $ git rev-parse origin/develop
        f691151474605e4b4c04d6b523fb43495fc0b813

         $ git rev-parse origin/master
        f691151474605e4b4c04d6b523fb43495fc0b813

so it would not technically be a problem doing it.  However, merging
into another branch is not possible from GitHub's web interface as far
as I can see -- we would need to use the `git` command line to merge
into a different branch, or re-do the pull request...

**Comment by sparkvilla** [comment]
This was tested and merged into develop

**Pull request closed without merging**
