### PR TITLE
Include non python sources in pkg

### PR DESCRIPTION
**Pull request by riccardomurri**
See commit message of 4333ab0 for more details.

### CODE REVIEW

**Comment by hackermd** [comment]
Thanks Riccardo!

Just a minor point: Could you please set version to `0.3.1rc`, so that it is clear that this is not yet officially released.

**Comment by hackermd** [comment]
Thanks!

What is the reason for moving Python code out of /src/python?

I am asking because we use the same structure in `jtmodules` and `tmclient` packages. We should then change the structure of these repositories as well.

**Comment by riccardomurri** [comment]
> What is the reason for moving Python code out of /src/python?

I was not able to find a combination of options for setup.py/setuptools that would pick Python code in `src/python` *and also* include non-Python files from parallel directories.  Despite what documentation says, tools do not seem to handle this case.

**Comment by hackermd** [comment]
Ok! I'll merge this. Could you please apply the same changes to the other two repos (`jtmodules` and `tmclient`) as well?

**Comment by hackermd** [comment]
Modules `filter` and `segmentation` were left in `src/python/jtlib`. I included them into the new package location with d39ed5e7f947a4cf287af8f1d842b914249cd7d5.

**Comment by hackermd** [comment]
Wait! Why do you actually want to distribute non-Python source files together with the Python package? If somebody wants to use the Matlab code, he can simple clone the repository and add the directory to the Matlab path.

**Pull request merged**
