### PR TITLE
Spot count v0.3.0

### PR DESCRIPTION
**Pull request by scottberry**
Added Nico and Thomas' module as a native matlab jterator module. Seems very robust on TissueMAPS v0.2.2 (I have run large experiments), and also runs on v0.3.0 (I have done some small tests).

I added the subfolder src/matlab/+cpsub to hold "cell profiler" subfunctions from the Pelkmans lab repository that are necessary for identify_spots_2D.m (the new main module in Jtmodules)

### CODE REVIEW

**Comment by scottberry** [comment]
requires https://github.com/TissueMAPS/JtModules/pull/10

**Comment by sparkvilla** [comment]
@hackermd it has been a while that is hanging there, shall we merge it to master?

**Comment by hackermd** [comment]
@sparkvilla we can add this to `devel`. However, I would first like to discuss to which extend we will generally support Matlab modules in the main repository. So far, we don't have an automated testing framework in place that could cover these modules, due to difficulties with respect to testing Matlab code in containers or any other environment outside of our private cloud.

**Comment by sparkvilla** [comment]
@scottberry I tried to rebase this one on the current develop but there are confilts. Would it be possible to make a new pull request on the current develop branch?

**Comment by scottberry** [comment]
@riccardomurri Previously we decided to only put matlab modules along with “in development” or private python modules in a private pelkmans lab jtmodules repo and to configure jterator to load modules from multiple sources. That way many users can have write access to the private repo, and can easily make their custom modules available on chimp (for example). I can close this pull request and send another to the private repo when it is configured in this way.

Scott

**Comment by sparkvilla** [comment]
@scottberry Yes, please. It would be great.

**Comment by scottberry** [comment]
@sparkvilla, I have now added all of the required files from jtmodules into the updated jtlibrary repository structure. Once you have a chance to setup the private repository, I can send a pull request there

**Pull request closed without merging**
